language: python

sudo: required
dist: trusty

group: edge

deploy:
  provider: pages
  # local_dir: ${TRAVIS_BUILD_DIR}/docs/build/html
  local_dir: /docs/build/html
  skip_cleanup: true
  repo: nickcafferry/Python-videos-for-beginners
  target_branch: master
  github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
  on:
    branch: master
    condition: ${TRAVIS_PYTHON_VERSION} = "3.78"

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update -qq

install:
 - sudo apt-get install -qq gcc gfortran libblas-dev liblapack-dev
 - sudo apt-get install -qq gcc-4.8 gfortran-4.8
 - |
   if [ ${TRAVIS_PYTHON_VERSION:0:1} = 3.8 ]; then
       sudo apt-get install python3-numpy
       pip3 install scipy
       python3 setup.py build
       python3 setup.py install
       pip3 install sphinx
       pip3 install sphinx-rtd-theme
       cd ${TRAVIS_BUILD_DIR}/docs
       make html
   elif [ ${TRAVIS_PYTHON_VERSION} = "3.7" ]; then
       sudo apt-get install python-numpy
       pip2 install scipy
       python2 setup.py build
       python2 setup.py install
       pip2 install sphinx
       pip2 install sphinx-rtd-theme
       cd ${TRAVIS_BUILD_DIR}/docs
       make html
   else
       echo "ERROR: Unknown Python version."
   fi
before_script:
 - cd ${TRAVIS_BUILD_DIR}/tests/

script:
 - nosetests -v

notifications:
  email: false
