name: audios downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: audios downloader

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        
        cd ./docs/
        
        ls
        echo '============================================'
        
        #mkdir assets
        #mkdir assets/audios
        cd assets/audios/
        mkdir 20150530
        cd 20150530/
        wget -O 20190518.zip http://audiocdn.economist.com/sites/default/files/AudioArchive/2015/20150530/Issue_8940_20150530_The_Economist_Full_edition.zip
        unzip 20190518.zip
        git add -A
        git rm -f 20190518.zip
  
        cd ../../../../
        git status 
        git commit -m "Add 20200829 "
        ls
        git push origin master
